---
# tasks file for install_vm_programs, you need to restart pc to get groups added.
- name: Install KVM utilities
  ansible.builtin.package:
    name: 
    - bridge-utils
    - cpu-checker
    - libvirt-clients
    - libvirt-daemon
    - qemu-system
    - qemu-kvm
    - virt-manager
    state: present
  become: true

- name: Add install user to kvm group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "kvm"
    append: true
  become: true

- name: Add install user to libvirtd group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "libvirt-qemu"
    append: true
  become: true

- name: Add install user to libvirtd group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "libvirt"
    append: true
  become: true
