---
# tasks file for git_shortcuts
- name: Add alias section to .gitconfig file
  ansible.builtin.blockinfile:
    path: ~/.gitconfig
    marker: '# {mark} Added via Ansible'
    create: true
    block: |
      [alias]
        hist = log --graph --color --date=short --pretty=format:'%Cred%h%Creset %C(bold green)%ad%Creset | %s%C(yellow)%d%Creset %C(bold blue)[%aN]'
        co = checkout
        ci = commit
        st = status
        br = branch
        type = cat-file -t
        dump = cat-file -p