---
# tasks file for install_common_programs
- name: Add my commonly used programs...
  ansible.builtin.package:
    update_cache: true
    name: 
    - tmux
    - vlc
    - htop
    - cpu-checker
    - git
    - gtypist
    - vim
    - tree
    - python-is-python3
    - net-tools
    - iputils-arping
    - openssh-server
  become: true

- name: Add line numbers to vim 
  ansible.builtin.lineinfile:
    path: ~/.vimrc
    create: true
    line: set number
