---
# tasks file for install_common_programs
- name: Add my commonly used programs...
  ansible.builtin.package:
    name: 
    - tmux
    - vlc
    - htop
    - cpu-checker
    - git
    - gtypist
    - vim
  become: true

- name: Add line numbers to vim 
  ansible.builtin.blockinfile:
    path: ~/.vimrc
    marker: '# {mark} Added via Ansible'
    create: true
    block: |
      set number
